### PR TITLE
Backporting the changes made in #139

### PR DESCRIPTION
**Pull request by LeShadow**
Backporting the changes made in #139 so this functionality is also accessible in the 1.2.x releases.

This fix allows for more compliance with the DNS RFC. Explanation here: https://github.com/egulias/EmailValidator/pull/139/commits/08bac068c26edd210daa259a2819d7dfd7438091

### CODE REVIEW

**Comment by LeShadow** [comment]
@egulias it seems that one of the tests in travis-ci fails due to a composer problem?

**Comment by egulias** [comment]
Hi @LeShadow , yes, the build for PHP 5.4 with  `composer install` fails because the lock file contains  dependencies requiring PHP 5.5 and above. Can you please remove the modified lock file (not doing a `composer update` but `install`)?

**Comment by LeShadow** [comment]
@egulias i fixed the composer.lock problem :-)

**Comment by egulias** [comment]
@LeShadow are you deleting the file content?

**Comment by LeShadow** [comment]
@egulias my apologies, this should be fixed now :).

**Comment by egulias** [comment]
Hey! great, now only one file modified! I can merge it. Thanks for taking the time!

**Pull request merged**
