### PR TITLE
Allow PHP 8 for the upcoming 3.0

### PR DESCRIPTION
**Pull request by darthsoup**
Bump the versions in the composer file to allow travis to build with php 8

### CODE REVIEW

**Comment by darthsoup** [comment]
as far as I can see now, PHP8 should now work with Travis. But cannot do anything against scrutinizer :/

**Comment by egulias** [comment]
Hi @darthsoup , thanks for the help.
For what I can read, while they say "any other realesed" they might not be ready for PHP8 yet https://scrutinizer-ci.com/docs/build/languages#php
Besides that, looks like psalm is failing, can you please check and fix? Much appreciated!

**Comment by egulias** [comment]
Nevermind, is another story. I'll figure it out and then merge yours, I think there's some missing config file to help here.

**Comment by darthsoup** [comment]
when i execute psalm from local, everything is ok

**Comment by egulias** [comment]
Great work @darthsoup , merged!

**Pull request merged**
