### PR TITLE
[WIP] Fix intl support

### LINKED ISSUE #177: Using polyfill for ext-intl if
As I stated before in #175 it could be problematic to just disable functionality when the extension is not available on the system. (We had the problem after upgrading from 2.1.4 to 2.1.5.)

Using a polyfill like https://github.com/symfony/polyfill-intl-icu could make this package work out of the box and still use the original functions from ext-intl if available. The suggestion for ext-intl in the composer.json should of course be kept.

The question is wether or not the polyfill from above or another one would make the code work.

For example the package symfony/intl does the same, see https://github.com/symfony/intl/blob/master/composer.json

### PR DESCRIPTION
**Pull request by GrahamCampbell**
TODO:
  - [x] Add intl polyfill dependency
  - [x] Remove checks on extension loaded
  - [ ] Find or write a polyfill for Spoofchecker

---

Closes #177. Closes https://github.com/egulias/EmailValidator/pull/229.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
@ohartl why have you approved this?

**Comment by ohartl** [comment]
> @ohartl why have you approved this?

As this would solve #177, i reviewed this for my pr for my specific use case and it works for that.

@GrahamCampbell Except UndefinedClass Spoofchecker stuff, but that seems to be fixable on symfony/polyfill project side right?

**Comment by GrahamCampbell** [comment]
Symfony have no plans to implement the spoofing class (which is totally fair enough), and so I don't think this PR can progress.

**Comment by egulias** [comment]
Thanks for updating @GrahamCampbell

**Pull request closed without merging**
