### PR TITLE
Move files in typical src and tests folder

### PR DESCRIPTION
**Pull request by simonschaufi**

### CODE REVIEW

**Comment by simonschaufi** [comment]
Surprisingly psalm throws the same errors in master branch as well so I didn't break it!

**Comment by egulias** [comment]
Hi @simonschaufi  I think it makes sense.
It would be amazing if you fix the psalm error too ;).

**Comment by simonschaufi** [comment]
To be honest, I don't understand the error message from psalm.

**Comment by simonschaufi** [comment]
@egulias would you agree with merging this one and I'll try my best to find a solution in another PR

**Comment by egulias** [comment]
I understand the problem is here https://github.com/egulias/EmailValidator/blob/c8d2ff978dfae1fbb48dbe64c1dbfeca780ce95b/src/Parser/Parser.php#L25
The docblock says that it is an array of "Warning" type, however, the comparission is being done against an int from a constant. I think it needs a dockblock of type "array" instead. 
Makes sense?

**Comment by simonschaufi** [comment]
yes, this fixes it! Thank you for your help!

**Comment by egulias** [comment]
Great news! All green! There we go.
Thanks @simonschaufi

**Pull request merged**
