### PR TITLE
Email addresses with single quote should not be valid

### PR DESCRIPTION
**Pull request by davpsh**
Fixes issue #215

### CODE REVIEW

**Comment by egulias** [comment]
Hi @davpsh, thanks for contributing! 
Please fix the error encountered by Psalm (you can run it locally too):

> ERROR: TypeDoesNotContainType - src/Validation/DNSCheckValidation.php:123:35 - Type non-empty-list<array<array-key, mixed>> for $dnsRecords is never falsy (see https://psalm.dev/056)
    if (empty($dnsRecords) || !$dnsRecords) {

Thanks!

**Comment by davpsh** [comment]
> Hi @davpsh, thanks for contributing!
> Please fix the error encountered by Psalm (you can run it locally too):
> 
> > ERROR: TypeDoesNotContainType - src/Validation/DNSCheckValidation.php:123:35 - Type non-empty-list<array<array-key, mixed>> for $dnsRecords is never falsy (see https://psalm.dev/056)
> > if (empty($dnsRecords) || !$dnsRecords) {
> 
> Thanks!

Hi @egulias. Changes to this code do not affect the code associated with the error in psalm.

This error is from master branch - [here](https://travis-ci.org/github/davpsh/EmailValidator/jobs/736962169) is a travis-ci build from fork and for master branch.

I don't know why this variable and condition was added there. [Here](https://travis-ci.org/github/davpsh/EmailValidator/builds/736962776) is the passed build with removed condition.

**Comment by egulias** [comment]
Hi @davpsh,
You will see some commits of mine in your repo for this PR, while working to fix the psalm thing.
What I can see is that there has been an update in psalm related to void return type, it's been removed for v4 (https://github.com/vimeo/psalm/issues/4432) and won't come back. I'll continue to work on this PR to fix it, by specifying psalm version in composer.

**Review by egulias — APPROVED** [review]

**Comment by egulias** [comment]
Sucess!

**Pull request merged**
