### PR TITLE
[2.1] Removed unneeded repositories section from composer.json

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by egulias** [comment]
Hi Graham, 
this repositorie is required for this
https://github.com/egulias/EmailValidator/blob/master/Tests/Performance/AgainstOldIsemail.php.

What would you suggest?

**Comment by GrahamCampbell** [comment]
The repository is not "required", since it is published on packagist. This why the tests still pass on travis. :)

**Comment by GrahamCampbell** [comment]
Do you see what I mean?

**Comment by egulias** [comment]
Yes, you are right. However if I recall correctly, performance tests are not run as part of the build, since they are mostly "informative".
Thanks for you PRs!

**Comment by GrahamCampbell** [comment]
Right. So, I suppose I should say, this is why the compose install didn't fail on travis.

**Comment by GrahamCampbell** [comment]
Since the test itself didn't actually run, as you say. :)

**Pull request merged**
