### PR TITLE
Fix PHP 7.4 support for 1.x

### PR DESCRIPTION
**Pull request by mlocati**
Backport #203 to 1.x

### CODE REVIEW

**Comment by egulias** [comment]
Is this a Travis issue or a problem with Ubuntu´s version?

**Comment by mlocati** [comment]
I haven't inspected what's going wrong with the failing travisci jobs.
Maybe it was a transient problem? Could you try to restart the jobs?

**Comment by egulias** [comment]
Yes, did it. Same error, a missing global var. Will take a look later.

**Comment by mlocati** [comment]
What about https://github.com/egulias/EmailValidator/pull/207 ?

**Comment by egulias** [comment]
It passes. A substantial config change was need as I see. I´ll take a look to scrutinizer. Should I close this one and we continue in #207 ?

**Comment by mlocati** [comment]
IMHO #206 and #207 fix two separate issues.
I'd merge #207 and rebase #206 so that tests for php 7.4 passes

**Comment by egulias** [comment]
Merged #207 so you now can update.
Thanks for patience!

**Comment by mlocati** [comment]
PR rebased. BTW it seems that TravisCI is still having [connectivity issues](https://www.traviscistatus.com/).

@egulias could you try to restart the failing TravisCI jobs?

**Pull request merged**
