### PR TITLE
Regenerate lockfile for PHP 7.3

### PR DESCRIPTION
**Pull request by derrabus**
🤞🏻

### CODE REVIEW

**Comment by egulias** [comment]
Man, you are fast!

**Comment by derrabus** [comment]
I've also regenerated the Psalm baseline because it didn't match the locked Psalm version anymore. That should (hopefully) get us a green CI.

**Comment by derrabus** [comment]
All right. Apart from a hanging Travis runner that I cannot really fix, the CI is back to green now.

**Comment by derrabus** [comment]
After 3.x has been reset, I don't think we still need this PR. Closing.

**Pull request closed without merging**
